import { defineConfig } from "vitepress";
import * as fs from "node:fs";
import * as path from "node:path";

// This config is the single shared presentation-layer template (per the
// build spec: "This template's design does not change between runs. Only
// two things vary per site: the generated Markdown content, and the site
// title/metadata."). Which site's content it serves is picked at build/dev
// time via SITE=<output-folder-name>, e.g. `SITE=rijksmuseum npm run dev`.
//
// srcDir is set to the WHOLE per-site output folder (not just content/) so
// that content/*.md and the crawler's pages/<slug>/screenshot.png sit under
// one root Vite can always resolve and copy into the build — screenshots
// referenced from outside srcDir are not reliably servable/buildable.
// `rewrites` then strips the content/ prefix so routes stay clean
// (content/pages/homepage.md -> /pages/homepage) without moving any files.
const SITE = process.env.SITE || "rijksmuseum";
const outputRoot = path.resolve(__dirname, "../../output", SITE);
const contentDir = path.join(outputRoot, "content");

if (!fs.existsSync(contentDir)) {
  throw new Error(`No content found for SITE="${SITE}" at ${contentDir}. Run the crawler + analyzer for this site first.`);
}

const meta = fs.existsSync(path.join(outputRoot, "site.json"))
  ? JSON.parse(fs.readFileSync(path.join(outputRoot, "site.json"), "utf-8"))
  : { title: `${SITE} — Site Inventory`, description: "Site inventory generated by site-inventory-tool." };

function titleFromFrontmatter(filePath: string, fallback: string): string {
  const raw = fs.readFileSync(filePath, "utf-8");
  const match = raw.match(/^---\n[\s\S]*?title:\s*(.+?)\s*\n[\s\S]*?---/);
  return match ? match[1].replace(/^["']|["']$/g, "") : fallback;
}

function sidebarSection(subdir: string, base: string) {
  const dir = path.join(contentDir, subdir);
  if (!fs.existsSync(dir)) return [];
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort();
  return files.map((file) => {
    const slug = file.replace(/\.md$/, "");
    const fallback = slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
    const title = titleFromFrontmatter(path.join(dir, file), fallback);
    return { text: title, link: `${base}/${slug}` };
  });
}

const pagesSidebarItems = sidebarSection("pages", "/pages");
const componentsSidebarItems = sidebarSection("components", "/components");

export default defineConfig({
  title: meta.title,
  description: meta.description,
  srcDir: outputRoot,
  outDir: path.resolve(outputRoot, "site-dist"),
  cleanUrls: true,
  rewrites: (id) => {
    if (id === "content/overview.md") return "index.md";
    if (id.startsWith("content/")) return id.slice("content/".length);
    return id;
  },
  themeConfig: {
    nav: [
      { text: "Overview", link: "/" },
      { text: "Components", link: componentsSidebarItems[0]?.link || "/components/" },
      { text: "Pages", link: pagesSidebarItems[0]?.link || "/pages/" },
    ],
    sidebar: {
      "/pages/": [{ text: `Pages (${pagesSidebarItems.length})`, items: pagesSidebarItems }],
      "/components/": [{ text: `Components (${componentsSidebarItems.length})`, items: componentsSidebarItems }],
    },
    search: { provider: "local" },
    outline: { level: [2, 3] },
  },
});
